import Link from "next/link";

export default async function PilotThankYou({searchParams}:{searchParams:Promise<{org?:string}>}){
  const {org}=await searchParams;
  const calendar=process.env.NEXT_PUBLIC_COMASY_CALENDAR_URL;
  return <main className="page"><section><Link href="/comasy" className="brand">KONFYDENCE <span>/ CoMaSy</span></Link><p className="eye">PILOT REQUEST RECEIVED</p><h1>Your pilot request is in.</h1><p className="lead">{org?`We have recorded the request for ${org}. `:""}The next step is to turn the request into a defined enterprise evaluation—not a generic software demo.</p><div className="next"><article><b>01</b><h2>Review the use case</h2><p>We check the buyer objective, current programme and intended cohort.</p></article><article><b>02</b><h2>Agree the cohort and risk focus</h2><p>Department, role, geography and the pressure situations worth rehearsing.</p></article><article><b>03</b><h2>Establish pilot measures</h2><p>Participation, Pause Adoption, Verification, Impulse and trigger-specific movement.</p></article><article><b>04</b><h2>Configure the programme</h2><p>Baseline, targeted practice, follow-up and the final results review.</p></article></div>{calendar?<a className="cta" href={calendar} rel="noopener noreferrer">Book a 20-minute scoping call <span>→</span></a>:<div className="notice"><b>Request recorded in Konfydence OS.</b><span>The account team will use the details you submitted to arrange scoping. A calendar link is shown here only when scheduling is configured.</span></div>}<Link className="back" href="/comasy">Back to CoMaSy</Link></section><style>{`
  :global(*){box-sizing:border-box}:global(body){margin:0;background:#071d31}.page{min-height:100vh;background:radial-gradient(circle at 85% 12%,#174d72,transparent 32%),#071d31;color:white;font-family:Inter,system-ui,sans-serif;padding:32px}.page section{width:min(980px,100%);margin:0 auto}.brand{display:inline-block;color:white;text-decoration:none;font-size:11px;font-weight:950}.brand span{color:#b8ff3d}.eye{margin:90px 0 14px;color:#b8ff3d;font-size:9px;letter-spacing:.14em;font-weight:950}.page h1{font:500 clamp(54px,8vw,88px)/.92 Georgia,serif;letter-spacing:-.05em;margin:0;max-width:820px}.lead{max-width:720px;color:#b6cad7;font-size:15px;line-height:1.7;margin:24px 0 42px}.next{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid #ffffff24}.next article{padding:24px 24px 24px 0;border-right:1px solid #ffffff1c}.next article:not(:first-child){padding-left:22px}.next article:last-child{border-right:0}.next b{font-size:9px;color:#ff685e}.next h2{font:500 23px/1.05 Georgia,serif;margin:22px 0 10px}.next p{font-size:10px;line-height:1.55;color:#93a9b7}.cta{display:inline-flex;align-items:center;gap:30px;background:#b8ff3d;color:#071d31;text-decoration:none;border-radius:999px;padding:14px 18px;font-size:11px;font-weight:950;margin-top:28px}.notice{margin-top:28px;border:1px solid #ffffff22;border-radius:13px;padding:16px;display:grid;gap:6px;max-width:680px}.notice b{font-size:11px}.notice span{font-size:10px;color:#9db0bc;line-height:1.5}.back{display:block;color:#9eb1bd;margin-top:28px;font-size:10px}@media(max-width:760px){.page{padding:22px 16px}.eye{margin-top:65px}.next{grid-template-columns:1fr 1fr}.next article{border-right:0;border-bottom:1px solid #ffffff18;padding:20px 16px 20px 0!important}}@media(max-width:480px){.next{grid-template-columns:1fr}.page h1{font-size:54px}}
`}</style></main>
}
