export const COUNTRY_LANDMARKS: Record<string, string> = {
  "algeria": "Casbah of Algiers",
  "angola": "Fortress of Sao Miguel",
  "benin": "Door of No Return",
  "botswana": "Okavango Delta",
  "burkina-faso": "Grand Mosque of Bobo-Dioulasso",
  "burundi": "Lake Tanganyika",
  "cabo-verde": "Cidade Velha",
  "cameroon": "Mount Cameroon",
  "central-african-republic": "Bangui Cathedral",
  "chad": "Ennedi Plateau",
  "comoros": "Mount Karthala",
  "republic-of-the-congo": "Odzala-Kokoua National Park",
  "democratic-republic-of-the-congo": "Virunga National Park",
  "cote-d-ivoire": "Basilica of Our Lady of Peace",
  "djibouti": "Lake Assal",
  "egypt": "Pyramids of Giza",
  "equatorial-guinea": "Malabo National Park",
  "eritrea": "Fiat Tagliero Building",
  "eswatini": "Sibebe Rock",
  "ethiopia": "Rock-Hewn Churches of Lalibela",
  "gabon": "Lope National Park",
  "gambia": "Kunta Kinteh Island",
  "ghana": "Cape Coast Castle",
  "guinea": "Mount Nimba",
  "guinea-bissau": "Bijagos Archipelago",
  "kenya": "Maasai Mara",
  "lesotho": "Maletsunyane Falls",
  "liberia": "Providence Island",
  "libya": "Leptis Magna",
  "madagascar": "Avenue of the Baobabs",
  "malawi": "Lake Malawi",
  "mali": "Great Mosque of Djenne",
  "mauritania": "Chinguetti",
  "mauritius": "Le Morne Brabant",
  "morocco": "Jemaa el-Fnaa",
  "mozambique": "Bazaruto Archipelago",
  "namibia": "Sossusvlei",
  "niger": "Agadez Grand Mosque",
  "nigeria": "Zuma Rock",
  "rwanda": "Volcanoes National Park",
  "sao-tome-and-principe": "Pico Cao Grande",
  "senegal": "Goree Island",
  "seychelles": "Vallee de Mai",
  "sierra-leone": "Tacugama Chimpanzee Sanctuary",
  "somalia": "Laas Geel",
  "south-africa": "Table Mountain",
  "south-sudan": "The Sudd",
  "sudan": "Meroe Pyramids",
  "tanzania": "Mount Kilimanjaro",
  "togo": "Koutammakou",
  "tunisia": "Amphitheatre of El Jem",
  "uganda": "Murchison Falls",
  "zambia": "Victoria Falls",
  "zimbabwe": "Great Zimbabwe",
  "afghanistan": "Blue Mosque of Mazar-i-Sharif",
  "armenia": "Geghard Monastery",
  "azerbaijan": "Flame Towers",
  "bahrain": "Bahrain Fort",
  "bangladesh": "The Sundarbans",
  "bhutan": "Tiger's Nest",
  "brunei": "Sultan Omar Ali Saifuddien Mosque",
  "cambodia": "Angkor Wat",
  "china": "Great Wall of China",
  "georgia": "Gergeti Trinity Church",
  "india": "Taj Mahal",
  "indonesia": "Borobudur Temple",
  "iran": "Nasir al-Mulk Mosque",
  "iraq": "Erbil Citadel",
  "israel": "Old City of Jerusalem",
  "japan": "Mount Fuji",
  "jordan": "Petra",
  "kazakhstan": "Charyn Canyon",
  "kuwait": "Kuwait Towers",
  "kyrgyzstan": "Issyk-Kul",
  "laos": "Kuang Si Falls",
  "lebanon": "Baalbek",
  "malaysia": "Petronas Twin Towers",
  "maldives": "Male Waterfront",
  "mongolia": "Genghis Khan Equestrian Statue",
  "myanmar": "Bagan Temples",
  "nepal": "Mount Everest",
  "north-korea": "Mount Paektu",
  "oman": "Sultan Qaboos Grand Mosque",
  "pakistan": "Badshahi Mosque",
  "palestine": "Dome of the Rock",
  "philippines": "Banaue Rice Terraces",
  "qatar": "Museum of Islamic Art",
  "saudi-arabia": "Al-Ula",
  "singapore": "Marina Bay Sands",
  "south-korea": "Gyeongbokgung Palace",
  "sri-lanka": "Sigiriya",
  "syria": "Palmyra",
  "tajikistan": "Iskanderkul",
  "thailand": "Grand Palace Bangkok",
  "timor-leste": "Cristo Rei Dili",
  "turkey": "Hagia Sophia",
  "turkmenistan": "Darvaza Gas Crater",
  "united-arab-emirates": "Burj Khalifa",
  "uzbekistan": "Registan Square",
  "vietnam": "Ha Long Bay",
  "yemen": "Socotra Archipelago",
  "albania": "Berat Old Town",
  "andorra": "Vallnord Mountains",
  "austria": "Schoenbrunn Palace",
  "belarus": "Mir Castle",
  "belgium": "Grand Place Brussels",
  "bosnia-and-herzegovina": "Mostar Old Bridge",
  "bulgaria": "Rila Monastery",
  "croatia": "Dubrovnik Old Town",
  "cyprus": "Petra tou Romiou",
  "czechia": "Charles Bridge",
  "denmark": "Nyhavn Copenhagen",
  "estonia": "Tallinn Old Town",
  "finland": "Suomenlinna",
  "france": "Eiffel Tower",
  "germany": "Brandenburg Gate",
  "greece": "Acropolis of Athens",
  "hungary": "Hungarian Parliament",
  "iceland": "Blue Lagoon",
  "ireland": "Cliffs of Moher",
  "italy": "Colosseum",
  "latvia": "Riga Old Town",
  "liechtenstein": "Vaduz Castle",
  "lithuania": "Trakai Island Castle",
  "luxembourg": "Luxembourg Old Town",
  "malta": "Hagar Qim Temples",
  "moldova": "Orheiul Vechi",
  "monaco": "Port Hercules",
  "montenegro": "Bay of Kotor",
  "netherlands": "Amsterdam Canals",
  "north-macedonia": "Lake Ohrid",
  "norway": "Geirangerfjord",
  "poland": "Wawel Castle",
  "portugal": "Belem Tower",
  "romania": "Bran Castle",
  "russia": "Saint Basil's Cathedral",
  "san-marino": "Guaita Tower",
  "serbia": "Belgrade Fortress",
  "slovakia": "Spis Castle",
  "slovenia": "Lake Bled",
  "spain": "Sagrada Familia",
  "sweden": "Gamla Stan Stockholm",
  "switzerland": "Matterhorn",
  "ukraine": "Saint Sophia Cathedral Kyiv",
  "united-kingdom": "Tower Bridge",
  "vatican-city": "St. Peter's Basilica",
  "antigua-and-barbuda": "Nelson's Dockyard",
  "bahamas": "Nassau Waterfront",
  "barbados": "Harrison's Cave",
  "belize": "Great Blue Hole",
  "canada": "Niagara Falls",
  "costa-rica": "Arenal Volcano",
  "cuba": "Old Havana",
  "dominica": "Boiling Lake",
  "dominican-republic": "Punta Cana Coastline",
  "el-salvador": "Santa Ana Volcano",
  "grenada": "Grand Anse Beach",
  "guatemala": "Tikal",
  "haiti": "Citadelle Laferriere",
  "honduras": "Copan Ruins",
  "jamaica": "Dunn's River Falls",
  "mexico": "Chichen Itza",
  "nicaragua": "Ometepe Island",
  "panama": "Panama Canal",
  "saint-kitts-and-nevis": "Brimstone Hill Fortress",
  "saint-lucia": "The Pitons",
  "saint-vincent-and-the-grenadines": "Tobago Cays",
  "trinidad-and-tobago": "Pitch Lake",
  "united-states": "Statue of Liberty",
  "argentina": "Perito Moreno Glacier",
  "bolivia": "Salar de Uyuni",
  "brazil": "Christ the Redeemer",
  "chile": "Torres del Paine",
  "colombia": "Cartagena Old Town",
  "ecuador": "Galapagos Islands",
  "guyana": "Kaieteur Falls",
  "paraguay": "Jesuit Missions of Trinidad",
  "peru": "Machu Picchu",
  "suriname": "Paramaribo Historic Centre",
  "uruguay": "Palacio Salvo",
  "venezuela": "Angel Falls",
  "australia": "Sydney Opera House",
  "fiji": "Yasawa Islands",
  "kiribati": "Kiritimati",
  "marshall-islands": "Bikini Atoll",
  "micronesia": "Nan Madol",
  "nauru": "Anibare Bay",
  "new-zealand": "Milford Sound",
  "palau": "Rock Islands",
  "papua-new-guinea": "Kokoda Track",
  "samoa": "To Sua Ocean Trench",
  "solomon-islands": "Marovo Lagoon",
  "tonga": "Ha'amonga'a Maui Trilithon",
  "tuvalu": "Funafuti Lagoon",
  "vanuatu": "Mount Yasur",
};
